In [1]:
# Importing essential libraries

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
import numpy as np

# Load the dataset

In [3]:
cancer = datasets.load_breast_cancer()

# Exploring Data /Data Analysis

In [4]:

print("Features: ", cancer.feature_names)


print("Labels: ", cancer.target_names)


Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Labels:  ['malignant' 'benign']


# Split the data into training/testing sets

In [5]:
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.25,random_state=109) 
print(X_test)

[[1.167e+01 2.002e+01 7.521e+01 ... 8.120e-02 3.206e-01 8.950e-02]
 [1.194e+01 1.824e+01 7.571e+01 ... 6.296e-02 2.785e-01 7.408e-02]
 [1.916e+01 2.660e+01 1.262e+02 ... 1.872e-01 3.258e-01 9.720e-02]
 ...
 [1.160e+01 2.449e+01 7.423e+01 ... 4.815e-02 3.244e-01 6.745e-02]
 [1.490e+01 2.253e+01 1.021e+02 ... 2.475e-01 2.866e-01 1.155e-01]
 [1.128e+01 1.339e+01 7.300e+01 ... 8.611e-02 2.102e-01 6.784e-02]]


# Generating Model

In [6]:
clf=svm.SVC(kernel='linear')

# Train the model using the training sets

In [7]:
clf.fit(X_train, y_train)

SVC(kernel='linear')

# Predict the response for test dataset

In [8]:
y_pred = clf.predict(X_test)

In [9]:

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


print("Precision:",metrics.precision_score(y_test, y_pred))


print("Recall:",metrics.recall_score(y_test, y_pred))

print("Confusiuon Matrix:",metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.958041958041958
Precision: 0.9770114942528736
Recall: 0.9550561797752809
Confusiuon Matrix: [[52  2]
 [ 4 85]]


In [10]:
input=[17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189]
input_data_as_numpy=np.asarray(input);
re=input_data_as_numpy.reshape(1,-1)
prediction=clf.predict(re)
if prediction[0]==0:
    print('malignant')
else:
    print('benign')


malignant
